@startuml 
title méthode calculerChemin
participant Boss <<(C,#ADD1B2)>>
participant "suiteDeDeplacement : Deque<Character>" as deplacements
participant Labyrinthe

activate Boss
Boss -> Boss : calculerChemin()
activate Boss
Boss -> deplacements : clear()
activate deplacements
deplacements --> Boss
deactivate deplacements

Boss -> Labyrinthe : getEmpreinte()
activate Labyrinthe
Labyrinthe --> Boss
deactivate Labyrinthe

Boss -> Boss : lee()
activate Boss
Boss -> Boss : retraceChemin()

@enduml