@startuml 
title Chargement lvl.json : réussi
participant JeuPrincipal << (C,#ADD1B2) >>

activate JeuPrincipal
JeuPrincipal -> JeuPrincipal : chargerLVL(int lvl)
activate JeuPrincipal

JeuPrincipal -> JeuPrincipal : chargerJSON(String url)
activate JeuPrincipal

JeuPrincipal -> JeuPrincipal : decodeJSON(JSONObject json)
activate JeuPrincipal


@enduml