@startuml 
title Création de Case
participant Labyrinthe << (C,#ADD1B2) >>
participant CaseVide << (C,#ADD1B2) >>
participant Mur << (C,#ADD1B2) >>

create CaseVide
Labyrinthe -> CaseVide : CaseVide()
activate CaseVide
CaseVide --> Labyrinthe 
deactivate CaseVide
create Mur
Labyrinthe -> Mur : Mur()
activate Mur
Mur --> Labyrinthe
deactivate Mur

@enduml