@startuml 
title Création du Labyrinthe
participant main
participant Labyrinthe << (C,#ADD1B2) >>
participant CaseVide << (C,#ADD1B2) >>

main -> Labyrinthe : Labyrinthe()
Activate Labyrinthe
Labyrinthe -> CaseVide : CaseVide()
activate CaseVide
CaseVide --> Labyrinthe
deactivate CaseVide
Labyrinthe --> main
deactivate Labyrinthe

@enduml