@startuml 
title Création de Monstre Suivi
participant "mainP:mainPerso" as mainP << (C,#ADD1B2) >>
participant "lab:Labyrinthe" as lab << (C,#ADD1B2) >>
participant "mss:MonstreSuivi" as mss << (C,#ADD1B2) >>

create lab
mainP -> lab : Labyrinthe()
Activate lab
loop
create mss
lab -> mss : MonstreAleatoire()
activate mss
mss --> lab
deactivate mss
end
lab --> mainP
deactivate lab
@enduml