@startuml 
title Création de Monstre Aléatoire
participant "mainP:mainPerso" as mainP << (C,#ADD1B2) >>
participant "lab:Labyrinthe" as lab << (C,#ADD1B2) >>
participant "msa:MonstreAleatoire" as msa << (C,#ADD1B2) >>

create lab
mainP -> lab : Labyrinthe()
Activate lab
loop
create msa
lab -> msa : MonstreAleatoire()
activate msa
msa --> lab
deactivate msa
end
lab --> mainP
deactivate lab
@enduml