@startuml 
title Deplacement de Monstre Aléatoire
participant "jeuM:JeuMonstre" as jeuM << (C,#ADD1B2) >> 
participant "ms:MonstreAleatoire" as msa << (C,#ADD1B2) >> 


jeuM-> msa : seDeplacer() 
activate msa
msa -> msa : attaquer()
activate msa
msa --> msa
deactivate msa
jeuM <-- msa
deactivate msa

@enduml