@startuml 
title Deplacement de Monstre Suivi
participant "jeuM:JeuMonstre" as jeuM << (C,#ADD1B2) >> 
participant "ms:MonstreSuivi" as mss << (C,#ADD1B2) >> 


jeuM-> mss : seDeplacer() 
activate mss
mss -> mss : attaquer()
activate mss
mss --> mss
deactivate mss
jeuM <-- mss
deactivate mss

@enduml