@startuml
title Fin du Labyrinthe
participant MoteurGraphique<< (C,#ADD1B2) >>
participant JeuPerso<< (C,#ADD1B2) >>
participant Aventurier<< (C,#ADD1B2) >>
participant Labyrinthe<< (C,#ADD1B2) >>

loop etreFini == false
activate MoteurGraphique 
MoteurGraphique -> JeuPerso : evoluer()
activate JeuPerso
JeuPerso -> Aventurier : getLab()
activate Aventurier
JeuPerso <-- Aventurier 
deactivate Aventurier
JeuPerso-> Labyrinthe : typeCase(x,y)


activate Labyrinthe

JeuPerso <-- Labyrinthe
deactivate Labyrinthe



MoteurGraphique <-- JeuPerso
deactivate JeuPerso
deactivate MoteurGraphique 

end
@enduml