@startuml
title Collision joueur Mur
participant Entite<< (C,#ADD1B2) >>
participant Labyrinthe<< (C,#ADD1B2) >>
participant Case<< (C,#ADD1B2) >>


 -> Entite: seDeplacer('') 
activate Entite
Entite-> Entite: peutAvancer(x,y)
Entite->Labyrinthe : estSurUnObstacle(x,y)
loop 
Labyrinthe-> Case :estDedans()
activate Case 
Labyrinthe<--Case 
deactivate Case 
Labyrinthe-> Case :peutTraverser()
activate Case 
Labyrinthe<--Case 
deactivate Case 
end
Entite<--Labyrinthe
 <-- Entite
deactivate Entite
@enduml