"plantuml.exportOutDir": "."
@startuml 
title Zeldiablo

interface Jeu {
    +evoluer(Commande): void
    +etreFini(): boolean
}

class JeuPrincipal {
    +JeuPrincipal()
}

class JeuPerso {
    -personnage: Aventurier
    +JeuPerso()
    +evoluer(Commande): void
    +etreFini(): boolean
}

interface DessinJeu {
    +dessine(BuffuredImage) : void
}

class DessinPerso {
    -jeuEnCours
    +DessinPerso(JeuPerso)
    +dessine(BuffuredImage): void
}

class Labyrinthe {
    -TAILLE_MIN: int
    -TAILLE_MAX: int
    +Labyrinthe(int, int)
}

class MonstreImmobile {
    -degat: int

    +MonstreImmobile(int, int, int, String, int)
    +attaquer(JeuPerso): void
}

abstract Case {
    #posX: int
    #posY: int
}

class CaseVide {
    +CaseVide(int, int)
}

class Mur {
    +Mur(int, int)
}

abstract Entite {
    #pv: int
    #x: int
    #y: int
    #nom: String
    #lab: Labyrinthe
    #vivant: boolean

    +Entite(int, int, int, String, Layrinthe)
    +seDeplacer(char): void
    +subirDegat(int): void
    +mort(): void
}

class Aventurier {
    +Aventurier(int, int int, String)
}

JeuPrincipal "1" --> "1" Labyrinthe : -lab
JeuPrincipal "1" --> "1" Aventurier : -av
JeuPrincipal "1" --> "0.." MonstreImmobile : -mi
JeuPerso "1" --> "1" Aventurier : -personnage
DessinPerso "1" --> "1" JeuPerso : -jeuEnCours
Labyrinthe "1" --> "0..*" Case : -cases

JeuPerso ..|> Jeu
DessinPerso ..|> DessinJeu
CaseVide --|> Case
Mur --|> Case
Aventurier --|> Entite
MonstreImmobile --|> Entite

@enduml